language: java
sudo: required
dist: trusty

before_install:
  - sudo service haveged start

script: ant -Divy.logging=default test

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-unlimited-jce-policy
      - haveged
      - bash-builtins
      - ant-optional

cache:
  apt: true
  directories:
    - $HOME/.ivy2

notifications:
  email: false

branches:
  only:
    - develop
